apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Claim will be created in the same namespace as the app.
# Crossplane will propagate the connection secret here too.
namespace: app-solthoth-hello-world-api-go

resources:
  - ../../base
